/* AbstractWriter.vala
 *
 * Copyright 2022 Diego Iván <diegoivan.mae@gmail.com>
 *
 * This file is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation; either version 3 of the
 * License, or (at your option) any later version.
 *
 * This file is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * SPDX-License-Identifier: LGPL-3.0-or-later
 */

public abstract class Valentine.AbstractWriter : Object {
    public virtual Valentine.WriteMode write_mode { get; set; }
    public virtual Valentine.SeparatorMode separator_mode { get; set; }

    /**
     * Writes a CSV string based on the information given to this
     *
     */
    public abstract string to_string ();

    /**
     * Saves the string generated by #this to the given path
     *
     * @param path The expected file path.
     *
     */
    public virtual void save_to_file (string path) throws Error {
        FileUtils.set_contents (path, to_string ());
    }
}
